### ISSUE TITLE
Unknown configuration section 'hostmanager'.

### ISSUE THREAD

**Issue by rbarlow** [purpleidea/oh-my-vagrant#87]
When I try to use OMV on my F21/libvirt system with a fairly vanilla omv.yaml file, I get an error:

```
$ vagrant status
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'hostmanager'.
```

I've noticed that if I comment out this section in the OMV Vagrantfile, the issue seems to go away:

```
    #
    #   hostmanager
    #
    # TODO: does this plugin still mess up the real vagrant-libvirt hostname ?
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = false  # don't manage local /etc/hosts
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true   # manage all the hosts!
    config.hostmanager.fqdn_friendly = true     # fqdns need to work...
    config.hostmanager.domain_name = domain     # use this domain name!
    config.hostmanager.extra_hosts = [
        {
            :host => "#{vip_hostname}.#{domain}",
            :ip => "#{vip_ip}",
            :aliases => ["#{vip_hostname}"],
        }
    ]
```

There's a TODO comment in there, perhaps about the issue I am experiencing?

**Comment by purpleidea** [comment]
Run this script: https://github.com/purpleidea/oh-my-vagrant/blob/master/extras/patch-hostmanager.sh and your problems will be fixed :) This isn't well documented. If you'd like to send a patch to the FAQ, I'd appreciate it!

Cheers,
James

**Comment by rbarlow** [comment]
Hey @purpleidea!

I tried that script, but I seem to still have some sort of packaging issue:

```
$ vagrant status
/usr/share/gems/gems/bundler-1.7.6/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find hitimes-1.2.2 in any of the sources (Bundler::GemNotFound)
	from /usr/share/gems/gems/bundler-1.7.6/lib/bundler/spec_set.rb:85:in `map!'
	from /usr/share/gems/gems/bundler-1.7.6/lib/bundler/spec_set.rb:85:in `materialize'
	from /usr/share/gems/gems/bundler-1.7.6/lib/bundler/definition.rb:132:in `specs'
	from /usr/share/gems/gems/bundler-1.7.6/lib/bundler/definition.rb:177:in `specs_for'
	from /usr/share/gems/gems/bundler-1.7.6/lib/bundler/definition.rb:166:in `requested_specs'
	from /usr/share/gems/gems/bundler-1.7.6/lib/bundler/environment.rb:18:in `requested_specs'
	from /usr/share/gems/gems/bundler-1.7.6/lib/bundler/runtime.rb:13:in `setup'
	from /usr/share/gems/gems/bundler-1.7.6/lib/bundler.rb:121:in `setup'
	from /usr/share/gems/gems/bundler-1.7.6/lib/bundler/setup.rb:17:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
```

The script said it finished successfully, but in order to get it to finish I installed ruby-devel and libvirt-devel. hitimes doesn't seem to be yum installable in F21. Should the script have installed it to ~/.vagrant.d/gems for me, or am I supposed to do that, or something else?

**Comment by purpleidea** [comment]
Should be fixed in the latest F21 package updates. 'yum clean all' and 'yum update' to see.
Also paste your 'yum info vagrant' here please :)
